# Analisis de Datos

In [23]:
from vothmo.config import CENSO_DATA
import os

data_folders = os.listdir(CENSO_DATA)

files = {}

for folder in data_folders:
    fdr = CENSO_DATA / folder
    lfdr = os.listdir(fdr)
    folder_pth = fdr / lfdr[0]
    for file in os.listdir(folder_pth):
        files[file] = folder_pth / file

files

{'01_descripcioncampos_conteoscensales_prisionpreventiva2024.txt': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales_PrisionPreventiva2024-1/DatosAbiertos_DECEyEC_ConteosCensales_PrisionPreventiva2024/01_descripcioncampos_conteoscensales_prisionpreventiva2024.txt'),
 'datosabiertos_deceyec_conteoscensales_prisionpreventiva2024.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales_PrisionPreventiva2024-1/DatosAbiertos_DECEyEC_ConteosCensales_PrisionPreventiva2024/datosabiertos_deceyec_conteoscensales_prisionpreventiva2024.csv'),
 '01_descripcioncampos_conteoscensales_votoanticipado2024.txt': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales_VotoAnticipado2024/DatosAbiertos_DECEyEC_ConteosCensales_VotoAnticipado2024/01_descripcioncampos_conteoscensales_votoanticipado2024.txt'),
 'datosabiertos_deceyec_conteoscensales_votoanticipado2024.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales_VotoAnticipado2024/DatosAbiertos_DECEyEC_ConteosCensales_VotoAnticipado2024/datosabiertos_deceyec_conteoscensales_votoanticipado2024.csv'),
 '01_descripcioncampos_conteoscensales2009.txt': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/01_descripcioncampos_conteoscensales2009.txt'),
 'datosabiertos_deceyec_conteoscensales2009_ags.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_ags.csv'),
 'datosabiertos_deceyec_conteoscensales2009_bc.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_bc.csv'),
 'datosabiertos_deceyec_conteoscensales2009_bcs.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_bcs.csv'),
 'datosabiertos_deceyec_conteoscensales2009_camp.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_camp.csv'),
 'datosabiertos_deceyec_conteoscensales2009_cdmx.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_cdmx.csv'),
 'datosabiertos_deceyec_conteoscensales2009_chih.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_chih.csv'),
 'datosabiertos_deceyec_conteoscensales2009_chis.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_chis.csv'),
 'datosabiertos_deceyec_conteoscensales2009_coah.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_coah.csv'),
 'datosabiertos_deceyec_conteoscensales2009_col.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_col.csv'),
 'datosabiertos_deceyec_conteoscensales2009_dgo.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_dgo.csv'),
 'datosabiertos_deceyec_conteoscensales2009_gro.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_gro.csv'),
 'datosabiertos_deceyec_conteoscensales2009_gto.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_gto.csv'),
 'datosabiertos_deceyec_conteoscensales2009_hgo.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_hgo.csv'),
 'datosabiertos_deceyec_conteoscensales2009_jal.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_jal.csv'),
 'datosabiertos_deceyec_conteoscensales2009_mex.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_mex.csv'),
 'datosabiertos_deceyec_conteoscensales2009_mich.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_mich.csv'),
 'datosabiertos_deceyec_conteoscensales2009_mor.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_mor.csv'),
 'datosabiertos_deceyec_conteoscensales2009_nay.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_nay.csv'),
 'datosabiertos_deceyec_conteoscensales2009_nl.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_nl.csv'),
 'datosabiertos_deceyec_conteoscensales2009_oax.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_oax.csv'),
 'datosabiertos_deceyec_conteoscensales2009_pue.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_pue.csv'),
 'datosabiertos_deceyec_conteoscensales2009_qro.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_qro.csv'),
 'datosabiertos_deceyec_conteoscensales2009_qroo.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_qroo.csv'),
 'datosabiertos_deceyec_conteoscensales2009_sin.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_sin.csv'),
 'datosabiertos_deceyec_conteoscensales2009_slp.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_slp.csv'),
 'datosabiertos_deceyec_conteoscensales2009_son.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_son.csv'),
 'datosabiertos_deceyec_conteoscensales2009_tab.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_tab.csv'),
 'datosabiertos_deceyec_conteoscensales2009_tamps.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_tamps.csv'),
 'datosabiertos_deceyec_conteoscensales2009_tlax.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_tlax.csv'),
 'datosabiertos_deceyec_conteoscensales2009_ver.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_ver.csv'),
 'datosabiertos_deceyec_conteoscensales2009_yuc.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_yuc.csv'),
 'datosabiertos_deceyec_conteoscensales2009_zac.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_zac.csv'),
 '01_descripcioncampos_conteoscensales2012.txt': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/01_descripcioncampos_conteoscensales2012.txt'),
 'datosabiertos_deceyec_conteoscensales2012_ags.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_ags.csv'),
 'datosabiertos_deceyec_conteoscensales2012_bc.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_bc.csv'),
 'datosabiertos_deceyec_conteoscensales2012_bcs.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_bcs.csv'),
 'datosabiertos_deceyec_conteoscensales2012_camp.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_camp.csv'),
 'datosabiertos_deceyec_conteoscensales2012_cdmx.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_cdmx.csv'),
 'datosabiertos_deceyec_conteoscensales2012_chih.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_chih.csv'),
 'datosabiertos_deceyec_conteoscensales2012_chis.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_chis.csv'),
 'datosabiertos_deceyec_conteoscensales2012_coah.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_coah.csv'),
 'datosabiertos_deceyec_conteoscensales2012_col.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_col.csv'),
 'datosabiertos_deceyec_conteoscensales2012_dgo.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_dgo.csv'),
 'datosabiertos_deceyec_conteoscensales2012_gro.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_gro.csv'),
 'datosabiertos_deceyec_conteoscensales2012_gto.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_gto.csv'),
 'datosabiertos_deceyec_conteoscensales2012_hgo.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_hgo.csv'),
 'datosabiertos_deceyec_conteoscensales2012_jal.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_jal.csv'),
 'datosabiertos_deceyec_conteoscensales2012_mex.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_mex.csv'),
 'datosabiertos_deceyec_conteoscensales2012_mich.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_mich.csv'),
 'datosabiertos_deceyec_conteoscensales2012_mor.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_mor.csv'),
 'datosabiertos_deceyec_conteoscensales2012_nay.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_nay.csv'),
 'datosabiertos_deceyec_conteoscensales2012_nl.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_nl.csv'),
 'datosabiertos_deceyec_conteoscensales2012_oax.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_oax.csv'),
 'datosabiertos_deceyec_conteoscensales2012_pue.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_pue.csv'),
 'datosabiertos_deceyec_conteoscensales2012_qro.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_qro.csv'),
 'datosabiertos_deceyec_conteoscensales2012_qroo.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_qroo.csv'),
 'datosabiertos_deceyec_conteoscensales2012_sin.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_sin.csv'),
 'datosabiertos_deceyec_conteoscensales2012_slp.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_slp.csv'),
 'datosabiertos_deceyec_conteoscensales2012_son.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_son.csv'),
 'datosabiertos_deceyec_conteoscensales2012_tab.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_tab.csv'),
 'datosabiertos_deceyec_conteoscensales2012_tamps.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_tamps.csv'),
 'datosabiertos_deceyec_conteoscensales2012_tlax.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_tlax.csv'),
 'datosabiertos_deceyec_conteoscensales2012_ver.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_ver.csv'),
 'datosabiertos_deceyec_conteoscensales2012_yuc.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_yuc.csv'),
 'datosabiertos_deceyec_conteoscensales2012_zac.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_zac.csv'),
 '01_descripcioncampos_conteoscensales2015.txt': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2015/DatosAbiertos_DECEyEC_ConteosCensales2015/01_descripcioncampos_conteoscensales2015.txt'),
 'datosabiertos_deceyec_conteoscensales2015_ags.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2015/DatosAbiertos_DECEyEC_ConteosCensales2015/datosabiertos_deceyec_conteoscensales2015_ags.csv'),

In [25]:
filelist = list(files.keys())
filelist

data = [f for f in filelist if f.endswith(".csv")]
data

['datosabiertos_deceyec_conteoscensales_prisionpreventiva2024.csv',
 'datosabiertos_deceyec_conteoscensales_votoanticipado2024.csv',
 'datosabiertos_deceyec_conteoscensales2009_ags.csv',
 'datosabiertos_deceyec_conteoscensales2009_bc.csv',
 'datosabiertos_deceyec_conteoscensales2009_bcs.csv',
 'datosabiertos_deceyec_conteoscensales2009_camp.csv',
 'datosabiertos_deceyec_conteoscensales2009_cdmx.csv',
 'datosabiertos_deceyec_conteoscensales2009_chih.csv',
 'datosabiertos_deceyec_conteoscensales2009_chis.csv',
 'datosabiertos_deceyec_conteoscensales2009_coah.csv',
 'datosabiertos_deceyec_conteoscensales2009_col.csv',
 'datosabiertos_deceyec_conteoscensales2009_dgo.csv',
 'datosabiertos_deceyec_conteoscensales2009_gro.csv',
 'datosabiertos_deceyec_conteoscensales2009_gto.csv',
 'datosabiertos_deceyec_conteoscensales2009_hgo.csv',
 'datosabiertos_deceyec_conteoscensales2009_jal.csv',
 'datosabiertos_deceyec_conteoscensales2009_mex.csv',
 'datosabiertos_deceyec_conteoscensales2009_mich.csv',
 'datosabiertos_deceyec_conteoscensales2009_mor.csv',
 'datosabiertos_deceyec_conteoscensales2009_nay.csv',
 'datosabiertos_deceyec_conteoscensales2009_nl.csv',
 'datosabiertos_deceyec_conteoscensales2009_oax.csv',
 'datosabiertos_deceyec_conteoscensales2009_pue.csv',
 'datosabiertos_deceyec_conteoscensales2009_qro.csv',
 'datosabiertos_deceyec_conteoscensales2009_qroo.csv',
 'datosabiertos_deceyec_conteoscensales2009_sin.csv',
 'datosabiertos_deceyec_conteoscensales2009_slp.csv',
 'datosabiertos_deceyec_conteoscensales2009_son.csv',
 'datosabiertos_deceyec_conteoscensales2009_tab.csv',
 'datosabiertos_deceyec_conteoscensales2009_tamps.csv',
 'datosabiertos_deceyec_conteoscensales2009_tlax.csv',
 'datosabiertos_deceyec_conteoscensales2009_ver.csv',
 'datosabiertos_deceyec_conteoscensales2009_yuc.csv',
 'datosabiertos_deceyec_conteoscensales2009_zac.csv',
 'datosabiertos_deceyec_conteoscensales2012_ags.csv',
 'datosabiertos_deceyec_conteoscensales2012_bc.csv',
 'datosabiertos_deceyec_conteoscensales2012_bcs.csv',
 'datosabiertos_deceyec_conteoscensales2012_camp.csv',
 'datosabiertos_deceyec_conteoscensales2012_cdmx.csv',
 'datosabiertos_deceyec_conteoscensales2012_chih.csv',
 'datosabiertos_deceyec_conteoscensales2012_chis.csv',
 'datosabiertos_deceyec_conteoscensales2012_coah.csv',
 'datosabiertos_deceyec_conteoscensales2012_col.csv',
 'datosabiertos_deceyec_conteoscensales2012_dgo.csv',
 'datosabiertos_deceyec_conteoscensales2012_gro.csv',
 'datosabiertos_deceyec_conteoscensales2012_gto.csv',
 'datosabiertos_deceyec_conteoscensales2012_hgo.csv',
 'datosabiertos_deceyec_conteoscensales2012_jal.csv',
 'datosabiertos_deceyec_conteoscensales2012_mex.csv',
 'datosabiertos_deceyec_conteoscensales2012_mich.csv',
 'datosabiertos_deceyec_conteoscensales2012_mor.csv',
 'datosabiertos_deceyec_conteoscensales2012_nay.csv',
 'datosabiertos_deceyec_conteoscensales2012_nl.csv',
 'datosabiertos_deceyec_conteoscensales2012_oax.csv',
 'datosabiertos_deceyec_conteoscensales2012_pue.csv',
 'datosabiertos_deceyec_conteoscensales2012_qro.csv',
 'datosabiertos_deceyec_conteoscensales2012_qroo.csv',
 'datosabiertos_deceyec_conteoscensales2012_sin.csv',
 'datosabiertos_deceyec_conteoscensales2012_slp.csv',
 'datosabiertos_deceyec_conteoscensales2012_son.csv',
 'datosabiertos_deceyec_conteoscensales2012_tab.csv',
 'datosabiertos_deceyec_conteoscensales2012_tamps.csv',
 'datosabiertos_deceyec_conteoscensales2012_tlax.csv',
 'datosabiertos_deceyec_conteoscensales2012_ver.csv',
 'datosabiertos_deceyec_conteoscensales2012_yuc.csv',
 'datosabiertos_deceyec_conteoscensales2012_zac.csv',
 'datosabiertos_deceyec_conteoscensales2015_ags.csv',
 'datosabiertos_deceyec_conteoscensales2015_bc.csv',
 'datosabiertos_deceyec_conteoscensales2015_bcs.csv',
 'datosabiertos_deceyec_conteoscensales2015_camp.csv',
 'datosabiertos_deceyec_conteoscensales2015_cdmx.csv',
 'datosabiertos_deceyec_conteoscensales2015_chih.csv',
 'datosabiertos_deceyec_conteoscensales2015_chis.csv',
 'datosabiertos_deceyec_conteoscensales2015_coah.csv',
 'datosabiertos_deceyec_conteoscensales2015_col.csv',
 'datosabiertos_deceyec_conteoscensales2015_dgo.csv',
 'datosabiertos_deceyec_conteoscensales2015_gro.csv',
 'datosabiertos_deceyec_conteoscensales2015_gto.csv',
 'datosabiertos_deceyec_conteoscensales2015_hgo.csv',
 'datosabiertos_deceyec_conteoscensales2015_jal.csv',
 'datosabiertos_deceyec_conteoscensales2015_mex.csv',
 'datosabiertos_deceyec_conteoscensales2015_mich.csv',
 'datosabiertos_deceyec_conteoscensales2015_mor.csv',
 'datosabiertos_deceyec_conteoscensales2015_nay.csv',
 'datosabiertos_deceyec_conteoscensales2015_nl.csv',
 'datosabiertos_deceyec_conteoscensales2015_oax.csv',
 'datosabiertos_deceyec_conteoscensales2015_pue.csv',
 'datosabiertos_deceyec_conteoscensales2015_qro.csv',
 'datosabiertos_deceyec_conteoscensales2015_qroo.csv',
 'datosabiertos_deceyec_conteoscensales2015_sin.csv',
 'datosabiertos_deceyec_conteoscensales2015_slp.csv',
 'datosabiertos_deceyec_conteoscensales2015_son.csv',
 'datosabiertos_deceyec_conteoscensales2015_tab.csv',
 'datosabiertos_deceyec_conteoscensales2015_tamps.csv',
 'datosabiertos_deceyec_conteoscensales2015_tlax.csv',
 'datosabiertos_deceyec_conteoscensales2015_ver.csv',
 'datosabiertos_deceyec_conteoscensales2015_yuc.csv',
 'datosabiertos_deceyec_conteoscensales2015_zac.csv',
 'datosabiertos_deceyec_conteoscensales2018_ags.csv',
 'datosabiertos_deceyec_conteoscensales2018_bc.csv',
 'datosabiertos_deceyec_conteoscensales2018_bcs.csv',
 'datosabiertos_deceyec_conteoscensales2018_camp.csv',
 'datosabiertos_deceyec_conteoscensales2018_cdmx.csv',
 'datosabiertos_deceyec_conteoscensales2018_chih.csv',
 'datosabiertos_deceyec_conteoscensales2018_chis.csv',
 'datosabiertos_deceyec_conteoscensales2018_coah.csv',
 'datosabiertos_deceyec_conteoscensales2018_col.csv',
 'datosabiertos_deceyec_conteoscensales2018_dgo.csv',
 'datosabiertos_deceyec_conteoscensales2018_gro.csv',
 'datosabiertos_deceyec_conteoscensales2018_gto.csv',
 'datosabiertos_deceyec_conteoscensales2018_hgo.csv',
 'datosabiertos_deceyec_conteoscensales2018_jal.csv',
 'datosabiertos_deceyec_conteoscensales2018_mex.csv',
 'datosabiertos_deceyec_conteoscensales2018_mich.csv',
 'datosabiertos_deceyec_conteoscensales2018_mor.csv',
 'datosabiertos_deceyec_conteoscensales2018_nay.csv',
 'datosabiertos_deceyec_conteoscensales2018_nl.csv',
 'datosabiertos_deceyec_conteoscensales2018_oax.csv',
 'datosabiertos_deceyec_conteoscensales2018_pue.csv',
 'datosabiertos_deceyec_conteoscensales2018_qro.csv',
 'datosabiertos_deceyec_conteoscensales2018_qroo.csv',
 'datosabiertos_deceyec_conteoscensales2018_sin.csv',
 'datosabiertos_deceyec_conteoscensales2018_slp.csv',
 'datosabiertos_deceyec_conteoscensales2018_son.csv',
 'datosabiertos_deceyec_conteoscensales2018_tab.csv',
 'datosabiertos_deceyec_conteoscensales2018_tamps.csv',
 'datosabiertos_deceyec_conteoscensales2018_tlax.csv',
 'datosabiertos_deceyec_conteoscensales2018_ver.csv',
 'datosabiertos_deceyec_conteoscensales2018_yuc.csv',
 'datosabiertos_deceyec_conteoscensales2018_zac.csv',
 'datosabiertos_deceyec_conteoscensales2021_ags.csv',
 'datosabiertos_deceyec_conteoscensales2021_bc.csv',
 'datosabiertos_deceyec_conteoscensales2021_bcs.csv',
 'datosabiertos_deceyec_conteoscensales2021_camp.csv',
 'datosabiertos_deceyec_conteoscensales2021_cdmx.csv',
 'datosabiertos_deceyec_conteoscensales2021_chih.csv',
 'datosabiertos_deceyec_conteoscensales2021_chis.csv',
 'datosabiertos_deceyec_conteoscensales2021_coah.csv',
 'datosabiertos_deceyec_conteoscensales2021_col.csv',
 'datosabiertos_deceyec_conteoscensales2021_dgo.csv',
 'datosabiertos_deceyec_conteoscensales2021_gro.csv',
 'datosabiertos_deceyec_conteoscensales2021_gto.csv',
 'datosabiertos_deceyec_conteoscensales2021_hgo.csv',
 'datosabiertos_deceyec_conteoscensales2021_jal.csv',
 'datosabiertos_deceyec_conteoscensales2021_mex.csv',
 'datosabiertos_deceyec_conteoscensales2021_mich.csv',
 'datosabiertos_deceyec_conteoscensales2021_mor.csv',
 'datosabiertos_deceyec_conteoscensales2021_nay.csv',
 'datosabiertos_deceyec_conteoscensales2021_nl.csv',
 'datosabiertos_deceyec_conteoscensales2021_oax.csv',
 'datosabiertos_deceyec_conteoscensales2021_pue.csv',
 'datosabiertos_deceyec_conteoscensales2021_qro.csv',
 'datosabiertos_deceyec_conteoscensales2021_qroo.csv',
 'datosabiertos_deceyec_conteoscensales2021_sin.csv',
 'datosabiertos_deceyec_conteoscensales2021_slp.csv',
 'datosabiertos_deceyec_conteoscensales2021_son.csv',
 'datosabiertos_deceyec_conteoscensales2021_tab.csv',
 'datosabiertos_deceyec_conteoscensales2021_tamps.csv',
 'datosabiertos_deceyec_conteoscensales2021_tlax.csv',
 'datosabiertos_deceyec_conteoscensales2021_ver.csv',
 'datosabiertos_deceyec_conteoscensales2021_yuc.csv',
 'datosabiertos_deceyec_conteoscensales2021_zac.csv',
 'datosabiertos_deceyec_conteoscensales2024_ags.csv',
 'datosabiertos_deceyec_conteoscensales2024_bc.csv',
 'datosabiertos_deceyec_conteoscensales2024_bcs.csv',
 'datosabiertos_deceyec_conteoscensales2024_camp.csv',
 'datosabiertos_deceyec_conteoscensales2024_cdmx.csv',
 'datosabiertos_deceyec_conteoscensales2024_chih.csv',
 'datosabiertos_deceyec_conteoscensales2024_chis.csv',
 'datosabiertos_deceyec_conteoscensales2024_coah.csv',
 'datosabiertos_deceyec_conteoscensales2024_col.csv',
 'datosabiertos_deceyec_conteoscensales2024_dgo.csv',
 'datosabiertos_deceyec_conteoscensales2024_gro.csv',
 'datosabiertos_deceyec_conteoscensales2024_gto.csv',
 'datosabiertos_deceyec_conteoscensales2024_hgo.csv',
 'datosabiertos_deceyec_conteoscensales2024_jal.csv',
 'datosabiertos_deceyec_conteoscensales2024_mex.csv',
 'datosabiertos_deceyec_conteoscensales2024_mich.csv',
 'datosabiertos_deceyec_conteoscensales2024_mor.csv',
 'datosabiertos_deceyec_conteoscensales2024_nay.csv',
 'datosabiertos_deceyec_conteoscensales2024_nl.csv',
 'datosabiertos_deceyec_conteoscensales2024_oax.csv',
 'datosabiertos_deceyec_conteoscensales2024_pue.csv',
 'datosabiertos_deceyec_conteoscensales2024_qro.csv',
 'datosabiertos_deceyec_conteoscensales2024_qroo.csv',
 'datosabiertos_deceyec_conteoscensales2024_sin.csv',
 'datosabiertos_deceyec_conteoscensales2024_slp.csv',
 'datosabiertos_deceyec_conteoscensales2024_son.csv',
 'datosabiertos_deceyec_conteoscensales2024_tab.csv',
 'datosabiertos_deceyec_conteoscensales2024_tam.csv',
 'datosabiertos_deceyec_conteoscensales2024_tlax.csv',
 'datosabiertos_deceyec_conteoscensales2024_ver.csv',
 'datosabiertos_deceyec_conteoscensales2024_yuc.csv',
 'datosabiertos_deceyec_conteoscensales2024_zac.csv']

In [27]:
son_data = [d for d in data if d.endswith("_son.csv")]
son_data

['datosabiertos_deceyec_conteoscensales2009_son.csv',
 'datosabiertos_deceyec_conteoscensales2012_son.csv',
 'datosabiertos_deceyec_conteoscensales2015_son.csv',
 'datosabiertos_deceyec_conteoscensales2018_son.csv',
 'datosabiertos_deceyec_conteoscensales2021_son.csv',
 'datosabiertos_deceyec_conteoscensales2024_son.csv']

In [ ]:
test1 = son_data[-2]  # 2021
test2 = son_data[-1]  # 2024
import pandas as pd

In [37]:

df1 = pd.read_csv(files[test1], low_memory=False)
df2 = pd.read_csv(files[test2], low_memory=False)

In [41]:
df1['DEL'].unique()

array([18,  7,  3,  4,  5,  8, 10,  9, 12,  6, 11,  2,  1, 14, 16, 17, 15,
       13, 21, 20, 19])

In [40]:
df2['DEL'].unique()

array([nan,  2.,  3.,  4.,  7., 18., 11., 13., 14., 21.,  8.,  9., 10.,
       15., 16., 17., 19., 20.,  6.,  1.,  5., 12.])

In [67]:
sect1 = set(df1[df1['DEL'] == 6]['SECCION'].astype(int))

In [70]:
sect2 = set(df2[df2['DEL'] == 6]['SECCION'].astype(int))
sect2

{353,
 354,
 355,
 356,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 1356,
 1357,
 1358,
 1359,
 1360,
 1361,
 1505,
 1506,
 1507}

In [73]:
for u, v in zip(sect1, sect2):
    print(u, v)

1400 1356
517 1357
518 1358
519 1359
520 1360
521 1361
522 353
523 354
524 355
525 356
526 362
527 363
528 364
1401 365
1402 366
531 367
532 368
533 369
534 370
535 371
536 373
537 374
538 375
539 376
540 377
1404 378
542 379
543 382
544 383
545 384
546 385
1405 386
549 387
550 388
551 389
552 396
553 397
554 398
555 399
556 400
557 401
559 402
560 403
561 404
562 405
566 406
567 422
568 423
569 424
570 425
572 426
1403 427
1512 428
499 429
500 430
501 431
502 432
503 433
504 434
505 435
506 436
1396 437
1397 444
1398 445
1399 446

In [76]:
hmo1 = df1[df1['MPIONOM'] == "Hermosillo"]
hmo1

,AELEC,FELECCION,EDOCVE,EDONOM,MPIOCVE,MPIONOM,SECCION,TIPOSEC,DEF,DEL,SEXO,EDAD,LN,SV,NV,NS
42198,2021,6/6/2021,26,SONORA,49,Hermosillo,336,U,3,8,0,18,60,22,38,0
42199,2021,6/6/2021,26,SONORA,49,Hermosillo,336,U,3,8,0,19,78,17,61,0
42200,2021,6/6/2021,26,SONORA,49,Hermosillo,336,U,3,8,0,20,90,19,71,0
42201,2021,6/6/2021,26,SONORA,49,Hermosillo,336,U,3,8,0,21,109,22,87,0
42202,2021,6/6/2021,26,SONORA,49,Hermosillo,336,U,3,8,0,22,106,27,79,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204655,2021,6/6/2021,26,SONORA,49,Hermosillo,1556,U,5,12,1,77,1,0,1,0
204656,2021,6/6/2021,26,SONORA,49,Hermosillo,1556,U,5,12,1,78,1,0,1,0
204657,2021,6/6/2021,26,SONORA,49,Hermosillo,1556,U,5,12,1,79,1,0,1,0
204658,2021,6/6/2021,26,SONORA,49,Hermosillo,1556,U,5,12,1,82,1,0,1,0
204659,2021,6/6/2021,26,SONORA,49,Hermosillo,1556,U,5,12,1,85,1,0,1,0

In [77]:
hmo2 = df2[df2['MPIONOM'] == "Hermosillo"]
hmo2

,AELEC,FELECCION,EDOCVE,EDONOM,MPIOCVE,MPIONOM,SECCION,TIPOSEC,DEF,DEL,SEXO,EDAD,LN,SV,NV,NS
24,2024,06/02/2024,26,SONORA,49,Hermosillo,618,M,3,11.0,0,27,8,4,4,0
25,2024,06/02/2024,26,SONORA,49,Hermosillo,618,M,3,11.0,0,52,5,4,1,0
26,2024,06/02/2024,26,SONORA,49,Hermosillo,604,M,3,11.0,0,78,4,1,3,0
27,2024,06/02/2024,26,SONORA,49,Hermosillo,599,M,3,11.0,0,83,1,1,0,0
28,2024,06/02/2024,26,SONORA,49,Hermosillo,590,M,3,11.0,0,42,120,71,39,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214739,2024,06/02/2024,26,SONORA,49,Hermosillo,1579,U,5,10.0,1,62,19,1,2,16
214740,2024,06/02/2024,26,SONORA,49,Hermosillo,1579,U,5,10.0,1,29,28,1,7,20
214741,2024,06/02/2024,26,SONORA,49,Hermosillo,1514,U,5,11.0,1,68,5,5,0,0
214742,2024,06/02/2024,26,SONORA,49,Hermosillo,1504,U,5,11.0,1,80,1,0,1,0
214743,2024,06/02/2024,26,SONORA,49,Hermosillo,1513,U,5,11.0,1,80,2,2,0,0

In [ ]:
hmo2['DEL'].unique()

array([11.,  8.,  9., 10.,  6., 12., nan])

In [79]:
hmo1['DEL'].unique()

array([ 8, 10,  9, 12,  6, 11])

In [86]:
history = {8: [],
10: [],
9: [],
12: [],
11: [],
6: [],
0: []}


for s in son_data:
    df = pd.read_csv(files[s], low_memory=False)
    hmo = df[df['MPIONOM'] == "Hermosillo"]
    dfs = hmo['DEL'].unique()
    for ds in dfs:
        hmo_ds = hmo[hmo["DEL"] == ds]
        try:
            history[int(ds)].append(len(hmo_ds['SECCION'].unique()))
        except:
            history[0].append(len(hmo_ds['SECCION'].unique()))

In [87]:
history

{8: [38, 38, 75, 75, 75, 78],
 10: [40, 38, 40, 40, 40, 80],
 9: [87, 87, 93, 93, 93, 58],
 12: [54, 51, 65, 65, 65, 52],
 11: [31, 32, 79, 79, 78, 73],
 6: [54, 63, 65, 65, 65, 92],
 0: [8, 6, 0]}